spring:
  application:
    name: poll-management-api

  datasource:
    url: jdbc:mysql://localhost:3306/poll_schema?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sistema123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    schemas: poll_schema
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0

server:
  address: 0.0.0.0
  port: 5000

info:
  app:
    name: poll-management-api

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
