spring:
  application:
    name: poll-management-api

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: 

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    show-sql: true
    
  h2.console:
    enabled: true
    path: /h2

  flyway:
    schemas: testdb
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

server:
  address: 0.0.0.0
  port: 5000

info:
  app:
    name: poll-management-api

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
